# Generated by Django 5.2.15 on 2026-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_userdashboardlayout_itens_ocultos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardlayout',
            name='cards_ocultos_dashboard',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
