# Generated by Django 5.2.15 on 2026-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_employeerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('executive', 'Visão Executiva (KPIs)'), ('exams', 'Exames Ocupacionais'), ('leave_inss', 'Afastamentos e INSS'), ('accidents', 'Acidentes e CAT'), ('absenteeism_health', 'Absenteísmo e Saúde dos Colaboradores')], max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
